### ISSUE TITLE
Animation with Customies addon

### ISSUE THREAD

**Issue by and7ey** [Endermanbugzjfc/NoBedrockBridging#4]
(sorry for raising issue here, I haven't found any other way to contact you)

I am working on my own addon and trying to use entity with animation there, but animation is not played.
I used your resource pack and it works well (your RP and my plugin). I compared your resource pack file against mine and see no difference. 

May I ask your help here?

**Comment by Endermanbugzjfc** [comment]
> (sorry for raising issue here, I haven't found any other way to contact you)
> 
> 
> 
> I am working on my own addon and trying to use entity with animation there, but animation is not played.
> 
> I used your resource pack and it works well (your RP and my plugin). I compared your resource pack file against mine and see no difference. 
> 
> 
> 
> May I ask your help here?

Sorry, I have been a bit busy these few days and didn't read this. Did you wish the animation to play as long as the entity spawns? If so, you could add a "setup" script in the entity's resource pack definition, like how I did so. Otherwise, you may try specifying triggers for those animations or actively sending animation packets. However, I am unsure of the exact method.
